import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import typescript from "@rollup/plugin-typescript";
import nodePolyfills from "rollup-plugin-polyfill-node";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
	input: "src/main.ts",
	inlineDynamicImports: true,
	output: [
		{
			file: "main.js",
			sourcemap: "inline",
			format: "cjs",
			exports: "default",
			banner,
			compact: true,
		},
	],
	external: ["obsidian", "fs", "os", "path"],
	plugins: [json(), nodeResolve({ browser: true, preferBuiltins: true }), commonjs(), nodePolyfills("path"), typescript({ sourceMap: true })],
};
